# Generated by Django 5.2 on 2026-02-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_menu', models.ImageField(blank=True, null=True, upload_to='gambar/')),
                ('nama_menu', models.CharField(max_length=200)),
                ('dibaca', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ditambahkan_oleh', models.ManyToManyField(blank=True, related_name='menu_disimpan', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaraMasak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField()),
                ('deskripsi', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cara_masak', to='mealplan.namamenu')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=200)),
                ('jumlah', models.FloatField()),
                ('satuan', models.CharField(max_length=50)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahan', to='mealplan.namamenu')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.PositiveIntegerField()),
                ('carb', models.PositiveIntegerField()),
                ('lemak', models.PositiveIntegerField()),
                ('kalori', models.PositiveIntegerField()),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrisi', to='mealplan.namamenu')),
            ],
        ),
    ]
