# Generated by Django 5.2 on 2026-03-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterNutrisiBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bahan', models.CharField(max_length=200, unique=True)),
                ('berat_persajian', models.FloatField(help_text='contoh: 100 (gr/ml) atau 1 (butir)')),
                ('satuan', models.CharField(help_text='gr / ml / butir', max_length=20)),
                ('kalori', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='nutrisi',
            name='carb',
        ),
        migrations.AddField(
            model_name='bahan',
            name='master_nutrisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dipakai_di', to='mealplan.masternutrisibahan'),
        ),
    ]
