# Generated by Django 5.2 on 2026-03-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0002_masternutrisibahan_remove_nutrisi_carb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrisi',
            name='kalori',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='nutrisi',
            name='lemak',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrisi',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
