# Generated by Django 5.2 on 2026-03-02 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0003_alter_nutrisi_kalori_alter_nutrisi_lemak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bahan',
            options={'verbose_name_plural': 'Bahan'},
        ),
        migrations.AlterModelOptions(
            name='caramasak',
            options={'ordering': ['urutan'], 'verbose_name_plural': 'Cara Memasak'},
        ),
        migrations.AlterModelOptions(
            name='masternutrisibahan',
            options={'verbose_name_plural': 'Master Nutrisi Bahan'},
        ),
        migrations.AlterModelOptions(
            name='namamenu',
            options={'verbose_name_plural': 'Nama Menu'},
        ),
        migrations.AlterModelOptions(
            name='nutrisi',
            options={'verbose_name_plural': 'Nutrisi'},
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.CharField(blank=True, choices=[('diet', 'Diet'), ('bulking', 'Bulking')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pengguna',
            },
        ),
    ]
