# Generated by Django 5.2 on 2026-03-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0004_alter_bahan_options_alter_caramasak_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namamenu',
            name='lama_perkiraan_masak',
            field=models.IntegerField(default=0),
        ),
    ]
