# Generated by Django 5.2 on 2026-03-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0005_namamenu_lama_perkiraan_masak'),
    ]

    operations = [
        migrations.AddField(
            model_name='namamenu',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('diet', 'Diet'), ('bulking', 'Bulking')], max_length=20, null=True),
        ),
    ]
