# Generated by Django 5.2 on 2026-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0006_namamenu_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='masternutrisibahan',
            name='lemak',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='masternutrisibahan',
            name='serat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutrisi',
            name='serat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
