# Generated by Django 5.2 on 2026-03-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0007_masternutrisibahan_lemak_masternutrisibahan_serat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bahan',
            options={},
        ),
        migrations.RemoveField(
            model_name='bahan',
            name='nama_bahan',
        ),
    ]
