# Generated by Django 5.2 on 2026-03-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0008_alter_bahan_options_remove_bahan_nama_bahan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Menu',
            },
        ),
        migrations.AlterModelOptions(
            name='bahan',
            options={'verbose_name_plural': 'Bahan'},
        ),
        migrations.RemoveField(
            model_name='namamenu',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='namamenu',
            name='kategori',
            field=models.ManyToManyField(blank=True, related_name='menus', to='mealplan.kategorimenu'),
        ),
    ]
