# Generated by Django 5.2 on 2026-03-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0009_kategorimenu_alter_bahan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namamenu',
            name='ditambahkan_oleh',
        ),
    ]
