# Generated by Django 5.2 on 2026-03-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0010_remove_namamenu_ditambahkan_oleh'),
    ]

    operations = [
        migrations.AddField(
            model_name='namamenu',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
