# Generated by Django 5.2 on 2026-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0011_namamenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='namamenu',
            name='utama',
            field=models.BooleanField(default=False),
        ),
    ]
