# Generated by Django 5.2 on 2026-03-03 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0012_namamenu_utama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='namamenu',
            name='diloved_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diloved_olehs', to=settings.AUTH_USER_MODEL),
        ),
    ]
