# Generated by Django 5.2 on 2026-03-03 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0013_namamenu_diloved_oleh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namamenu',
            name='diloved_oleh',
        ),
        migrations.AddField(
            model_name='namamenu',
            name='diloved_oleh',
            field=models.ManyToManyField(blank=True, related_name='menus_dilove', to=settings.AUTH_USER_MODEL),
        ),
    ]
